const ERROR_CODES = {
  UNAUTHENTICATED: "UNAUTHENTICATED",
  BAD_USER_INPUT: "BAD_USER_INPUT",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
};

module.exports = { ERROR_CODES };
